# Helm Values Specific to Orders Microservice
configMapData:
  API_PORT: "31200"
  PORT_SERVER: "8080"

  PRODUCTS_SERVICE_HOST: products-service
  PRODUCTS_SERVICE_PORT: "8080"
  CUSTOMERS_SERVICE_HOST: customer-service
  CUSTOMERS_SERVICE_PORT: "8080"

  DATABASE_HOST: orders-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: "orders"
  DATABASE_USER: "postgres"
  DATABASE_DIALECT: "postgres"

  CACHE_HOST: tcl-orders.ynpq2p.ng.0001.use1.cache.amazonaws.com
  CACHE_PORT: "6379"
  CACHE_DATABASE: "1"
  CACHE_TLS: "true"

  MERCADO_PAGO_USER_ID: "2276121958"
  MERCADO_PAGO_ACCESS_TOKEN: "APP_USR-7010877515049958-021719-ca6f540e548c46267a3e54c2162cb2ba-2276121958"
  MERCADO_PAGO_POINT_OF_SALE_ID: "10203045"
  NOTIFICATION_URL_HOST: http://a46b3f6038f8646f08793f724206d017-1372074634.us-east-1.elb.amazonaws.com

secret:
  enabled: true
  data:
    DATABASE_PASSWORD: "TVRJek5EVTI="

externalServices:
  - name: orders-db
    externalName: order-database.cbwo208oqr0s.us-east-1.rds.amazonaws.com

image:
  repository: "301067586589.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-lanchonete/orders"
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  useStatefulSet: false

replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
