name: "Docker - Build & Push to Registry"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Microservice - Continuous Integration / Build"]
    branches: ["main"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION_DEFAULT: us-east-1
  AWS_ECR_REPOSITORY: tech-challenge-lanchonete/orders-vitorrafael
  AWS_ECR_REGISTRY: 045628470274.dkr.ecr.us-east-1.amazonaws.com

jobs:
  docker-build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Docker - Build & Push to ECR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Tag Image
        run: |
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:latest .

      - name: Push Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:latest
