name: "AWS EKS - Rollout Update"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker - Build & Push to Registry"]
    branches: ["main"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION_DEFAULT: us-east-1
  AWS_ECR_REPOSITORY: tech-challenge-lanchonete/orders-vitorrafael
  EKS_CLUSTER_NAME: tech-challenge-lanchonete

jobs:
  rollout-update:
    name: "Rollout Update"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Connect to AWS EKS Cluster
        if: github.ref == 'refs/heads/main'
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION_DEFAULT }}

      - name: Rollout Update
        if: github.ref == 'refs/heads/main'
        run: kubectl rollout restart deployment
